name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Debug Secrets
        run: 
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}"
            echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/new-web-scanner:latest
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/new-web-scanner:latest
              docker stop webscanner || true
              docker rm webscanner || true
              docker run -d -p 6969:80 --name webscanner ${{ secrets.DOCKERHUB_USERNAME }}/new-web-scanner:latest
        
